controllers:
    resource: ../src/Controller/
    type: attribute

recipe_random:
    path: /api/recipe
    methods: GET
    controller: App\Controller\RecipeController::getRecipe

add_recipe:
    path: /api/add-recipe
    methods: POST
    controller: App\Controller\RecipeController::addRecipe

