controllers:
    resource: ../src/Controller/
    type: attribute

recipe_random:
    path: /api/recipe
    methods: GET
    controller: App\Controller\RecipeController::getRecipe

all_recipes:
    path: /api/all-names-with-id
    methods: GET
    controller: App\Controller\RecipeController::getRecipeNamesWithId

add_recipe:
    path: /api/add-recipe
    methods: POST
    controller: App\Controller\RecipeController::addRecipe

find_by_name:
    path: /api/find-id-by-name
    methods: GET
    controller: App\Controller\RecipeController::findRecipeIdByName

find_by_id:
    path: /api/find-by-id
    methods: GET
    controller: App\Controller\RecipeController::findRecipeById

find_tag_by_name:
    path: /api/find-tags-by-name
    methods: GET
    controller: App\Controller\TagController::findTagsByName