controllers:
    resource: ../src/Controller/
    type: attribute

template_page:
    path: /template/page
    controller: App\Controller\TemplateController::templatePage

template_json:
    path: /template/json
    controller: App\Controller\TemplateController::templateJson

recipe_random:
    path: /recipe
    method: "GET"
    controller: App\Controller\RecipeController::getRecipe


add_recipe:
    path: /add-recipe
    method: "POST"
    controller: App\Controller\RecipeController::addRecipe
