### add Recipe
POST {{ip}}/api/add-recipe
Content-Type: application/json

{
  "name": "Name",
  "ingredients": "a- b- c",
  "instructions": "",
  "vegetarian": true
}

### get Recipe
GET http://localhost:8000/api/recipe
Accept: application/json

###

POST http://185.244.195.201/api/add-recipe
Content-Type: application/json

{
  "name": "test",
  "ingredients": "a- b- c",
  "instructions": "test the test",
  "vegetarian": true
}