### add Recipe
POST {{uri}}/api/add-recipe
Content-Type: application/json

{
  "name": "Aaaallererstes Testrezept",
  "ingredients": "a- b- c",
  "instructions": "teste!",
  "tags": [
    {
      "id": 1,
      "name": "omnivor"
    }
  ]
}

### get Recipe
GET {{uri}}/api/recipe?currentRecipe=1
Accept: application/json

### find Recipe by Name
GET {{uri}}/api/find-id-by-name?searchName=Chili
Accept: application/json

### find Recipe by id
GET {{uri}}/api/find-by-id?recipeId=2
Accept: application/json

### all Recipes with id
GET {{uri}}/api/all-names-with-id
Accept: application/json

### all Recipes with id filtered
GET {{uri}}/api/all-names-with-id?filterTags[]=vegan&filterTags[]=vegetarisch
Accept: application/json